import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect } from 'react'
import { useState } from 'react'
import { useRouter } from 'next/router'
import Logo from '@/storages/lequit.png'
import Modal from '@/components/Modal'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faAddressCard, faEnvelope, faMailBulk, faMailReply, faPhone } from '@fortawesome/free-solid-svg-icons'
import { faInstagram } from '@fortawesome/free-brands-svg-icons';


export default function Home() {

  const router = useRouter();

  useEffect(() => {
    // User Agent を取得
    const userAgent = window.navigator.userAgent;

    // スマートフォン以外の場合はリダイレクト
    if (!/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(userAgent)) {
      router.push('/unsupported-device'); // 非対応デバイス用のページにリダイレクト
    }
  }, []);

  const [isModalOpen, setIsModalOpen] = useState(false);

  const phoneNumber = '012012345678'; // ここに電話番号を設定

  const handleCall = () => {
    window.location.href = `tel:${phoneNumber}`;
  };

  const sendMail = () => {
    window.location.href = `mailto:itsuki-k@lequit.jp`;
  };

  const sendInstagram = () => {
    window.location.href = `https://www.instagram.com/itsuki_kb_ts`;
  };

  const openModal = () => {
    setIsModalOpen(true);
  };

  const closeModal = () => {
    setIsModalOpen(false);
  };
  return (
    <>
      <Head>
        <title>合同会社LEQUIT - 代表名刺</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.backgrounds}></div>
        <div className={styles.notes}>
          <div className={styles.logo}>
            <Image 
              src={Logo}
              alt='Lequitのロゴ'
              width={240} 
              height={125}
              className={styles.logo}
            ></Image>
          </div>
          <div className={styles["description_name"]}>代表社員</div>
          <div className={styles.name}>小橋川 樹</div>
          <div className={styles.containerBtn}>
            <div className={styles.square} onClick={handleCall}>
              <FontAwesomeIcon icon={faPhone} className={styles.minimum}/>
              <p className={styles.title}>Phone Call</p>
            </div>
            <div className={styles.square} onClick={sendInstagram}>
              <FontAwesomeIcon icon={faInstagram} className={styles.minimum}/>
              <p className={styles.title}>Instagram</p>
            </div>
          </div>
          <div className={styles.containerBtn}>
            <div className={styles.square} onClick={sendMail}>
              <FontAwesomeIcon icon={faEnvelope} className={styles.minimum}/>
              <p className={styles.title}>Send Mail</p>
            </div>
            <div className={styles.square} onClick={openModal}>
              <FontAwesomeIcon icon={faAddressCard} className={styles.minimum}/>
              <p className={styles.title}>Other</p>
            </div>
          </div>
          
          <Modal isOpen={isModalOpen} onClose={closeModal}>
            <h3 className={styles["text-center"]}>詳細内容</h3>
            <div className={styles.description_box}></div>
          </Modal>
        </div>
      </main>
    </>
  )
}
