import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import errStyles from '@/styles/Error.module.css'
import Card from '@/components/Card'

export default function UnSupported() {
    const title="エラー"
    const description="このデバイスではコンテンツの閲覧に対応しておりません。\nスマートフォンをご利用ください。"
    return (
      <>
        <Head>
          <title>Sorry...</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
        <Card
            title={title}
            description={description}
        />
        </main>
      </>
    )
  }